unifiedocs:
  target: dev
  outputs:
    dev:
      account: nl90696.ap-southeast-2
      client_session_keep_alive: false
      connect_retries: 0
      connect_timeout: 10
      database: UNIFIEDOCS_DEMO
      password: BradlovesKaela1
      retry_all: false
      retry_on_database_errors: false
      role: ACCOUNTADMIN
      schema: STAGING
      type: snowflake
      user: Brad
      warehouse: COMPUTE_WH
